"""Hardcoded /rig-mesh — orchestrator. Deterministic-first; AI behind ai_gate.

Generated by services/rig_commands/_template.py — do not hand-edit. Regenerate
via `python -m services.rig_commands._codegen <slug>`.
"""

from __future__ import annotations

import json
import subprocess
import sys
import time
from pathlib import Path

from services.rig_commands._runner import (
    Runner, ai_gate, args_nonempty, deterministic, emit_artifact, guardrails,
    output_has_artifact,
)

SLUG = "rig-mesh"
ARCHETYPE = "orchestrator"
DESCRIPTION = 'Run the full RIG Deviation Engine pipeline — deviate to ±30σ, then mesh candidates into 3-7 high-RIG-L synthesized outputs via Coral Reef (Engine 30) + Cuckoo (Engine 29) + Lévy (Engine 22). Use when you need novel ideas, not just scored ar'
RUNS_DIR = Path.home() / "Desktop/Startup-Intelligence-OS/artifacts/rig-studio-review/runs/rig-mesh"
V3_CLI = Path('/Users/mikerodgers/Desktop/Startup-Intelligence-OS/artifacts/rig_engines_v3/cli.py')

from services.rig_commands._router import route_with_tiebreaker


@guardrails(
    cost_cap_usd=0.02,             # routing decisions are mostly deterministic
    human_gate=False,
    pre_validate=[args_nonempty],
    post_verify=[output_has_artifact],
    fallback_on_ai_fail=True,
)
def main(r: Runner, args: list) -> dict:
    payload = deterministic(r, "parse_args", lambda: {"task": " ".join(args)})
    run_dir = RUNS_DIR / time.strftime("%Y%m%dT%H%M%S")
    run_dir.mkdir(parents=True, exist_ok=True)
    # Deterministic config lookup — AI fires only when resolve() returns ≥2 candidates.
    route = deterministic(
        r,
        "lookup_route",
        lambda: route_with_tiebreaker(SLUG, ARCHETYPE, payload, runner=r),
    )
    decision_path = run_dir / "decision.json"
    deterministic(r, "write_decision", lambda: decision_path.write_text(
        json.dumps({"payload": payload, "route": route}, indent=2)))
    emit_artifact(r, decision_path)
    return {"ok": True, "artifact": str(decision_path), "route": route}


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
