"""Hardcoded /rig-audit — audit. Deterministic-first; AI behind ai_gate.

Generated by services/rig_commands/_template.py — do not hand-edit. Regenerate
via `python -m services.rig_commands._codegen <slug>`.
"""

from __future__ import annotations

import json
import subprocess
import sys
import time
from pathlib import Path

from services.rig_commands._runner import (
    Runner, ai_gate, args_nonempty, deterministic, emit_artifact, guardrails,
    output_has_artifact,
)

SLUG = "rig-audit"
ARCHETYPE = "audit"
DESCRIPTION = 'Audit a file against 40 RIG Deviator™ strict engines (±25σ). Shortcut for `/rig-strict audit`.'
RUNS_DIR = Path.home() / "Desktop/Startup-Intelligence-OS/artifacts/rig-studio-review/runs/rig-audit"
V3_CLI = Path('/Users/mikerodgers/Desktop/Startup-Intelligence-OS/artifacts/rig_engines_v3/cli.py')

@guardrails(
    cost_cap_usd=0.0,             # AUDIT NEVER CALLS AI
    human_gate=False,
    pre_validate=[args_nonempty],
    post_verify=[output_has_artifact],
)
def main(r: Runner, args: list) -> dict:
    target = deterministic(r, "resolve_target", lambda: Path(args[0]).expanduser().resolve())
    if not target.exists():
        raise FileNotFoundError(target)
    out_json = deterministic(r, "alloc_output",
        lambda: RUNS_DIR / f"audit_{time.strftime('%Y%m%dT%H%M%S')}_{r.invocation_id}.json")
    if r.dry_run:
        emit_artifact(r, out_json)
        return {"ok": True, "artifact": str(out_json), "dry_run": True}
    RUNS_DIR.mkdir(parents=True, exist_ok=True)
    rc = deterministic(r, "run_v3_strict", lambda: subprocess.run(
        [sys.executable, str(V3_CLI), "audit", str(target),
         "--genre", "internal", "--json", str(out_json), "--summary-only"],
        capture_output=True, text=True, timeout=180, check=False,
    ).returncode)
    audit = deterministic(r, "load_audit", lambda: json.loads(out_json.read_text()))
    emit_artifact(r, out_json)
    return {"ok": True, "artifact": str(out_json),
            "rig_l": audit.get("rig_l"), "status": audit.get("status"),
            "hard_blocks": audit.get("hard_blocks"), "exit_code": rc}


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
