"""Hardcoded /rig-forecast-studio — studio. Deterministic-first; AI behind ai_gate.

Generated by services/rig_commands/_template.py — do not hand-edit. Regenerate
via `python -m services.rig_commands._codegen <slug>`.
"""

from __future__ import annotations

import json
import subprocess
import sys
import time
from pathlib import Path

from services.rig_commands._runner import (
    Runner, ai_gate, args_nonempty, deterministic, emit_artifact, guardrails,
    output_has_artifact,
)

SLUG = "rig-forecast-studio"
ARCHETYPE = "studio"
DESCRIPTION = 'Create forecasts, scenarios, probability councils, Brier scoring, and calibration loops.'
RUNS_DIR = Path.home() / "Desktop/Startup-Intelligence-OS/artifacts/rig-studio-review/runs/rig-forecast-studio"
V3_CLI = Path('/Users/mikerodgers/Desktop/Startup-Intelligence-OS/artifacts/rig_engines_v3/cli.py')

import json as _json
from services.rig_commands import _hermes_swarm


# ── per-studio subagent team map ──────────────────────────────────────────────
# Each entry: list of {role, model, prompt (optional)}
# model references: mesh-code (Blackwell), mesh-large (rig-256gb),
#                   cloud-claude (cloud/Anthropic), rig-96gb, rig-36gb

_STUDIO_TEAMS: dict[str, list[dict]] = {
    "rig-app-studio": [
        {"role": "planner",    "model": "mesh-large",  "prompt": "Produce a structured implementation plan with milestones and risks."},
        {"role": "scaffolder", "model": "mesh-code",   "prompt": "Generate the directory tree, file list, and boilerplate stubs."},
        {"role": "tester",     "model": "mesh-code",   "prompt": "Write test cases covering happy path, edge cases, and failure modes."},
        {"role": "deployer",   "model": "rig-36gb",    "prompt": "Specify CI/CD steps, environment variables, and rollback procedure."},
    ],
    "rig-design-studio": [
        {"role": "art-director",  "model": "mesh-large", "prompt": "Define visual language: palette, type scale, spacing system."},
        {"role": "ux-writer",     "model": "rig-96gb",   "prompt": "Write microcopy, labels, and empty states aligned with brand voice."},
        {"role": "motion-lead",   "model": "rig-36gb",   "prompt": "Specify animation curves, durations, and interaction feedback."},
        {"role": "design-critic", "model": "mesh-large", "prompt": "Identify inconsistencies and accessibility gaps in the proposed design."},
    ],
    "rig-engineering-studio": [
        {"role": "architect",    "model": "mesh-large", "prompt": "Define service boundaries, data flow, and API contracts."},
        {"role": "implementer",  "model": "mesh-code",  "prompt": "Produce concrete code modules with error handling and logging."},
        {"role": "reviewer",     "model": "mesh-code",  "prompt": "Review for hidden coupling, missing retries, and observability gaps."},
        {"role": "qa-lead",      "model": "rig-96gb",   "prompt": "Define integration and regression test strategy with coverage targets."},
        {"role": "ops-engineer", "model": "rig-36gb",   "prompt": "Specify deployment, monitoring alerts, and runbook for on-call."},
    ],
    "rig-gtm-studio": [
        {"role": "icp-analyst",    "model": "mesh-large", "prompt": "Sharpen ICP: firmographics, pain triggers, budget authority."},
        {"role": "offer-builder",  "model": "rig-96gb",   "prompt": "Construct the offer stack: headline, proof, objection handlers."},
        {"role": "channel-lead",   "model": "rig-36gb",   "prompt": "Map channel mix, sequencing cadence, and cost-per-lead targets."},
        {"role": "pipeline-model", "model": "mesh-large", "prompt": "Build a 90-day pipeline model with conversion assumptions."},
    ],
    "rig-forecast-studio": [
        {"role": "base-forecaster", "model": "mesh-large", "prompt": "Build base-case model with key drivers and assumptions logged."},
        {"role": "bear-forecaster", "model": "rig-96gb",   "prompt": "Construct bear-case scenario with probability and trigger conditions."},
        {"role": "bull-forecaster", "model": "rig-96gb",   "prompt": "Construct bull-case scenario with probability and trigger conditions."},
        {"role": "calibrator",      "model": "mesh-large", "prompt": "Score each scenario for Brier calibration. Flag overconfident claims."},
    ],
    "rig-strategy-studio": [
        {"role": "strategist",  "model": "mesh-large", "prompt": "Frame the strategic question, key uncertainties, and 2-3 wedge options."},
        {"role": "challenger",  "model": "mesh-large", "prompt": "Steel-man the worst objection to the leading strategy option."},
        {"role": "researcher",  "model": "rig-96gb",   "prompt": "Surface relevant precedents, analogues, and data points."},
        {"role": "executor",    "model": "rig-36gb",   "prompt": "Translate winning strategy into a 30/60/90-day action plan with owners."},
    ],
    "rig-product-studio": [
        {"role": "pm",          "model": "mesh-large", "prompt": "Write PRD with user stories, acceptance criteria, and success metrics."},
        {"role": "ux-lead",     "model": "rig-96gb",   "prompt": "Map user journey, key screens, and interaction flows."},
        {"role": "tech-lead",   "model": "mesh-code",  "prompt": "Estimate effort, identify blockers, and propose tech approach."},
        {"role": "data-lead",   "model": "rig-36gb",   "prompt": "Define instrumentation plan: events, funnels, and A/B hypotheses."},
    ],
    "rig-research-studio": [
        {"role": "librarian",   "model": "rig-96gb",   "prompt": "Identify primary and secondary sources; rate credibility."},
        {"role": "synthesizer", "model": "mesh-large", "prompt": "Extract themes, contradictions, and knowledge gaps across sources."},
        {"role": "critic",      "model": "mesh-large", "prompt": "Challenge synthesis: what evidence is missing or misread?"},
        {"role": "reporter",    "model": "rig-36gb",   "prompt": "Write structured research brief with executive summary and citations."},
    ],
    "rig-ops-studio": [
        {"role": "infra-lead",   "model": "mesh-code",  "prompt": "Audit current infrastructure; identify single points of failure."},
        {"role": "automator",    "model": "mesh-code",  "prompt": "Propose automation scripts and scheduled jobs to reduce toil."},
        {"role": "cost-analyst", "model": "rig-36gb",   "prompt": "Model monthly infrastructure cost and flag waste."},
        {"role": "sre-lead",     "model": "mesh-large", "prompt": "Define SLOs, error budgets, and incident runbooks."},
    ],
    "rig-website-studio": [
        {"role": "copywriter",    "model": "mesh-large", "prompt": "Draft page copy: hero, features, social proof, CTA."},
        {"role": "designer",      "model": "rig-96gb",   "prompt": "Specify layout structure, component hierarchy, and responsive rules."},
        {"role": "seo-lead",      "model": "rig-36gb",   "prompt": "Define meta strategy, heading hierarchy, and Core Web Vitals targets."},
        {"role": "dev-lead",      "model": "mesh-code",  "prompt": "Choose tech stack, generate component scaffold, and deployment config."},
    ],
    "rig-linkedin-studio": [
        {"role": "strategist",  "model": "mesh-large", "prompt": "Define content pillars, posting cadence, and engagement hooks."},
        {"role": "copywriter",  "model": "rig-96gb",   "prompt": "Draft 3 post variants: builder narrative, insight, and CTA-led."},
        {"role": "analyst",     "model": "rig-36gb",   "prompt": "Score each post for predicted reach, saves, and conversion rate."},
    ],
    "rig-instagram-studio": [
        {"role": "creative-lead", "model": "mesh-large", "prompt": "Define visual concept, caption hook, and hashtag strategy."},
        {"role": "copywriter",    "model": "rig-96gb",   "prompt": "Write caption variants for post, story, and reel formats."},
        {"role": "analyst",       "model": "rig-36gb",   "prompt": "Score each format for predicted reach and save rate."},
    ],
}

_DEFAULT_TEAM = [
    {"role": "planner",  "model": "mesh-large", "prompt": "Produce a structured plan with milestones and risks."},
    {"role": "executor", "model": "mesh-code",  "prompt": "Translate the plan into concrete actionable steps."},
    {"role": "critic",   "model": "rig-36gb",   "prompt": "Identify the top 3 gaps or risks in the proposed approach."},
]


def _team_for(slug: str, payload: str) -> list[dict]:
    """Return the subagent team for a given studio slug."""
    return _STUDIO_TEAMS.get(slug, _DEFAULT_TEAM)


def _merge_outputs(results: list[dict], payload: str) -> str:
    """Merge subagent outputs into a single structured markdown document."""
    lines = [
        f"# Studio Run — merged outputs",
        f"",
        f"**Task:** {payload}",
        f"",
        f"**Agents dispatched:** {len(results)}",
        f"**Transports used:** {', '.join(sorted({r.get('transport','?') for r in results}))}",
        f"",
        "---",
        "",
    ]
    for r in results:
        role = r.get("role", "agent")
        model = r.get("model", "?")
        elapsed = r.get("elapsed_s", 0.0)
        error = r.get("error")
        output = r.get("output", "").strip()
        lines.append(f"## {role} ({model}, {elapsed}s)")
        if error and error not in ("sequential_local_stub",):
            lines.append(f"_Error: {error}_")
        if output:
            lines.append("")
            lines.append(output)
        lines.append("")
        lines.append("---")
        lines.append("")
    return "\n".join(lines)


def _judge(text: str) -> dict:
    """Stub judge — real LLM call happens in ai_gate block; this is the fallback shape."""
    return {
        "score": None,
        "summary": text[:300].replace("\n", " "),
        "next_step": "Review merged.md and iterate with the relevant studio agent.",
    }


@guardrails(
    cost_cap_usd=0.10,
    human_gate=False,
    pre_validate=[args_nonempty],
    post_verify=[output_has_artifact],
    fallback_on_ai_fail=True,
)
def main(r: Runner, args: list) -> dict:
    payload = deterministic(r, "parse_args", lambda: " ".join(args))

    team = deterministic(r, "resolve_team", lambda: _team_for(SLUG, payload))

    run_dir = RUNS_DIR / time.strftime("%Y%m%dT%H%M%S")
    if not r.dry_run:
        run_dir.mkdir(parents=True, exist_ok=True)

    # Hermes Swarm fanout — the real multi-agent step
    if r.dry_run:
        results = [
            {"role": s["role"], "model": s["model"], "output": "[DRY_RUN]",
             "elapsed_s": 0.0, "error": None, "transport": "dry_run", "cost_usd": 0.0}
            for s in team
        ]
    else:
        results = deterministic(r, "swarm_fanout",
            lambda: _hermes_swarm.fanout(team, payload, timeout=120))

    merged_path = run_dir / "merged.md"
    deterministic(r, "synthesize",
        lambda: merged_path.write_text(_merge_outputs(results, payload)) if not r.dry_run else None)

    # Single AI judge pass — only LLM call (capped at $0.08 within $0.10 studio cap)
    judgment: dict = {"score": None, "next_step": "see merged.md"}
    try:
        with ai_gate(r, model="rig-256gb-large", reason="studio judge pass",
                     est_cost_usd=0.08) as g:
            if not r.dry_run:
                judgment = _judge(merged_path.read_text())
            g.output_summary = f"judged: {judgment.get('score')}"
    except Exception:
        pass

    judgment_path = run_dir / "judgment.json"
    deterministic(r, "write_judgment",
        lambda: judgment_path.write_text(_json.dumps(judgment, indent=2)) if not r.dry_run else None)

    emit_artifact(r, merged_path)
    emit_artifact(r, judgment_path)
    return {
        "ok": True,
        "artifact": str(merged_path),
        "judgment": str(judgment_path),
        "subagents_dispatched": len(team),
        "transport": list({res.get("transport", "?") for res in results}),
        "task": payload,
    }


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
